name: Lint

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      # Set env variable or otherwise tzdata package requires interaction
      env:
        DEBIAN_FRONTEND: noninteractive 
      run: |
        chmod +x ./.github/workflows/scripts/ubuntu_build_dependencies.sh
        sudo ./.github/workflows/scripts/ubuntu_build_dependencies.sh
        clang-format
    - name: configure
      run: ./configure
    - name: lint
      run: clang-format --version && make lint
